
/*Declare the custom (user defined) fonts*/
// #ifdef LV_FONT_CUSTOM_DECLARE
#ifndef MYFONT_H
#define MYFONT_H


LV_FONT_DECLARE(myfont)
LV_FONT_DECLARE(FiraMono_R_56)
LV_FONT_DECLARE(IBMPlexMono_R_56)
LV_FONT_DECLARE(PathwayGothicOne_R_56)
LV_FONT_DECLARE(PathwayGothicOne_R_64)
LV_FONT_DECLARE(PathwayGothicOne_R_72)
LV_FONT_DECLARE(PathwayGothicOne_R_80)

LV_FONT_DECLARE(SairaExtraCondensed_R_56)
LV_FONT_DECLARE(SalmaPro_R_56)

LV_FONT_DECLARE(montserrat_m_12)
LV_FONT_DECLARE(montserrat_b_12)

LV_FONT_DECLARE(DejaVuSans_R_12)
LV_FONT_DECLARE(DejaVuSans_R_14)
LV_FONT_DECLARE(DejaVuSans_R_16)
LV_FONT_DECLARE(DejaVuSans_R_18)
LV_FONT_DECLARE(DejaVuSans_R_20)
LV_FONT_DECLARE(DejaVuSans_R_22)
LV_FONT_DECLARE(DejaVuSans_R_24)

LV_FONT_DECLARE(Tauri_R_16)
LV_FONT_DECLARE(Tauri_R_18)
LV_FONT_DECLARE(Tauri_R_20)
LV_FONT_DECLARE(Tauri_R_22)
LV_FONT_DECLARE(Tauri_R_24)
LV_FONT_DECLARE(Tauri_R_26)

LV_FONT_DECLARE(Tauri_R_28)

LV_FONT_DECLARE(Tauri_R_40)
LV_FONT_DECLARE(Tauri_R_42)
LV_FONT_DECLARE(Tauri_R_44)
LV_FONT_DECLARE(Tauri_R_46)
LV_FONT_DECLARE(Tauri_R_48)
LV_FONT_DECLARE(Tauri_R_50)
LV_FONT_DECLARE(Tauri_R_52)
LV_FONT_DECLARE(Tauri_R_56)
LV_FONT_DECLARE(Tauri_R_58)
LV_FONT_DECLARE(Tauri_R_60)
LV_FONT_DECLARE(Tauri_R_62)
LV_FONT_DECLARE(Tauri_R_64)

LV_FONT_DECLARE(Tauri_R_70)
LV_FONT_DECLARE(f01_digit)
LV_FONT_DECLARE(f712_serif)
LV_FONT_DECLARE(nk57_mono)
LV_FONT_DECLARE(unscii_66)
LV_FONT_DECLARE(courier_prime)
LV_FONT_DECLARE(unscii_tall_64)
LV_FONT_DECLARE(unscii_8_64)
LV_FONT_DECLARE(unscii_tin_48)
LV_FONT_DECLARE(unscii_tin_49)
LV_FONT_DECLARE(unscii_tin_53)
LV_FONT_DECLARE(unscii_tin_54)
LV_FONT_DECLARE(unscii_tin_56)
LV_FONT_DECLARE(unscii_tin_58)
LV_FONT_DECLARE(unscii_tin_60)
LV_FONT_DECLARE(unscii_tin_62)
LV_FONT_DECLARE(unscii_tin_64)

LV_FONT_DECLARE(dseg_56)
LV_FONT_DECLARE(dseg_bold_56)

LV_FONT_DECLARE(dseg_r_12)
LV_FONT_DECLARE(dseg_r_56)

LV_FONT_DECLARE(dseg_b_48b1)
LV_FONT_DECLARE(dseg_b_48b1___)
LV_FONT_DECLARE(dseg_b_48b1__1)
LV_FONT_DECLARE(dseg_b_48b1_EH)
LV_FONT_DECLARE(dseg_b_48b1_H)
LV_FONT_DECLARE(dseg_b_48b4)
LV_FONT_DECLARE(dseg_b_48b4___)

LV_FONT_DECLARE(dseg_b_20)
LV_FONT_DECLARE(dseg_b_22)
LV_FONT_DECLARE(dseg_b_24)
LV_FONT_DECLARE(dseg_b_26)
LV_FONT_DECLARE(dseg_b_28)
LV_FONT_DECLARE(dseg_b_30)
LV_FONT_DECLARE(dseg_b_48)
LV_FONT_DECLARE(dseg_b_50)
LV_FONT_DECLARE(dseg_b_52)
LV_FONT_DECLARE(dseg_b_56)

LV_FONT_DECLARE(Born2bSportyV2_12)
LV_FONT_DECLARE(ChiKareGo2_10)
LV_FONT_DECLARE(ChiKareGo2_12)
LV_FONT_DECLARE(KarenFat_12)
LV_FONT_DECLARE(SullyVerge_12)
LV_FONT_DECLARE(WindyCity_12)

LV_FONT_DECLARE(Born2bSportyV2Modified_12)
LV_FONT_DECLARE(TenFatGuys_12)
LV_FONT_DECLARE(Macintosh128K_12)

LV_FONT_DECLARE(HabboPseudoMono_16)

LV_FONT_DECLARE(SNESesque_16b1)
LV_FONT_DECLARE(SNESesque_16b2)
LV_FONT_DECLARE(SNESesque_16b4)

LV_FONT_DECLARE(WindyCity_16b4)

LV_FONT_DECLARE(ATARISTOCRAT_8b4)

LV_FONT_DECLARE(ATARISTOCRAT_16bt)
LV_FONT_DECLARE(ATARISTOCRAT_24b4)
LV_FONT_DECLARE(ATARISTOCRAT_32b4)
LV_FONT_DECLARE(ATARISTOCRAT_64b4)

LV_FONT_DECLARE(unscii_8b4)
LV_FONT_DECLARE(unscii_16b4)

LV_FONT_DECLARE(c64esque_8b4)
LV_FONT_DECLARE(c64esque_12b4)
LV_FONT_DECLARE(c64esque_16b4)
LV_FONT_DECLARE(c64esque_24b4)
LV_FONT_DECLARE(c64esque_32b4)

LV_FONT_DECLARE(digital7_R_16)
LV_FONT_DECLARE(digital7_R_20)

LV_FONT_DECLARE(graph_R_8)
LV_FONT_DECLARE(graph_R_16)

LV_FONT_DECLARE(graph_R_18)
LV_FONT_DECLARE(graph_R_20)
LV_FONT_DECLARE(graph_R_35)

LV_FONT_DECLARE(monofont_R_16)
LV_FONT_DECLARE(monofont_R_20)

LV_FONT_DECLARE(zig_R_16)
LV_FONT_DECLARE(zig_R_20)

LV_FONT_DECLARE(Serifier_8b4)
LV_FONT_DECLARE(Serifier_16b4)
LV_FONT_DECLARE(Serifier_32b4)

LV_FONT_DECLARE(Undertale_12b)
LV_FONT_DECLARE(Undertale_16b1)
LV_FONT_DECLARE(Undertale_16b)
LV_FONT_DECLARE(Undertale_24b)
LV_FONT_DECLARE(Undertale_32b)

LV_FONT_DECLARE(unscii_14)

    // LV_FONT_CUSTOM_DECLARE
#endif